### ISSUE TITLE
Does the library provide a loadBitmap(String url) kind of method?

### ISSUE THREAD

**Issue by danielsunyu** [applidium/Shutterbug#5]
The most useful method, as documented in the README of the official repo, is the one-liner setImage(String url) of FetchableImageView class. It tackles 99% of real world needs. Voila! But occasionally, as in my case, I do need a method to load a Bitmap object of a previously cached image and pass it as a parameter to another app. I fail to find out a method in the API providing this functionality. One of my colleague added a piece of code in the ImageCache.java to complement it.

```
public Bitmap getCacheBitmap(String url) {
    String cacheKey = getCacheKey(url);
    if (cacheKey == null)
        return null;
    Bitmap bitMap = mMemoryCache.get(cacheKey);
    return bitMap;
}

private String getCacheKey(String url) {
    try {
        return URLEncoder.encode(url, "US-ASCII");
    } catch (UnsupportedEncodingException e) {
        e.printStackTrace();
        return null;
    }
}
```

Without fully understanding the intricacy of the library, the codes put here is certainly not a nice fit, but it works afterall, HAHA.

May the author of the library consider this, thank you!

**Comment by acq** [comment]
Hi
Thanks for the feedback !
Actually, there already is a way to do that : you can query the cache via `queryCache` (on ImageCache). You give it the cache key and an `ImageCacheListener` (which is able to call you back on different methods whether it found an image in the cache or not).
Here is an example :

```
ImageCache.getSharedImageCache(context).queryCache(ShutterbugManager.getCacheKey(url), new ImageCacheListener() {
    public void onImageNotFound(ImageCache imageCache, String key, DownloadRequest downloadRequest) {
    }

    public void onImageFound(ImageCache imageCache, Bitmap bitmap, String key, DownloadRequest downloadRequest) {
    }
}, null);
```

Also, you should not duplicate `getCacheKey`. I made it public (and static), so you can access it directly. Since the content of the method was changed recently, I encourage you to link back to the `ShutterbugManager` one.
