### ISSUE TITLE
This is not Google Maps v2.0 compatible.

### ISSUE THREAD

**Issue by mattwritescode** [applidium/Shutterbug#7]
This library will need to be upgraded to work with the new Google Maps version. It uses deprecated classes specifically in the FetchableOverlayItem class. I'm a fairly novice coder, so I'm probably not the best person to change this, but If I run into a solution I'll post it.

**Comment by acq** [comment]
Actually, FetchableOverlayItem would only be used for Google Maps v1 (there are no overlay items in Maps v2, but Markers, which behave quite differently).
Since Maps v1 has now been deprecated for quite some time, I don't see any reason for keeping this class in the project. Previous version is still available in history.
