### ISSUE TITLE
Out of Memory Error Due To BitMap 

### ISSUE THREAD

**Issue by rizvan** [applidium/Shutterbug#9]
Caused by: java.lang.OutOfMemoryError
at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:472)
at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:502)

**Comment by acq** [comment]
Hi. Thank you for your interest in Shutterbug.

As you can see from the stack trace, this Error is returned by Android, and not Shutterbug. This happens when you try to use images that are too big to be decompressed on your Android device. Often this is because the image you are trying to use contains several millions of pixels, which would make the decompressed bitmap several Mb.

There are several ways to fix this :
- the first one is to keep the library as it is and reduce the size of images you are using (which is the solution Google picked, with their OutOfMemoryError), but you're not always responsible for the source or format of the images used in your app.
- another one would be to intercept this error and try to decompress a smaller image (until success), which is sub-optimal since it would degrade the quality of images without telling you, or letting you be able to do anything.
- or we could provide you with alternative methods, which would let you define a max height and width for the display image (for example, the dimensions of your FetchableImageView). We are working on this solution and should release the update in the next couple of weeks.

Do you see another alternative ? Would one of the previous one solve your problem ?

**Comment by acq** [comment]
Solved via d781d7c369b64a7bea0353b15c262efba65e758a

As explained above, we chose to add methods making able to specify a maximum size for the images to be displayed.
